-----------------------------------------------------------------------------
----#####################---AUT_ELEMENTO_POLIZA_TP---###################-----
---JCCG 7/08/2018
-----------------------------------------------------------------------------
--####
--PASO 1---------------------------------------------------------------------
-- OBTIENE LOS DESCRIPTIVOS DE ALGUNOS ELEMENTOS DE LA TABLA KTCTGET
--TAKE 5MIN.
-- aut_elemento_poliza.sql
--03/02/2019 AMH: Se le agrego el elemento INSCORIN as ban_scorin
-----------------------------------------------------------------------------

DROP TABLE IF EXISTS BDDLALM.AUT_ELEMENTO_POLIZA_TMP;

INVALIDATE METADATA;

CREATE TABLE BDDLALM.AUT_ELEMENTO_POLIZA_TMP STORED AS PARQUET 
AS
SELECT
 A.NUM_POLIZA           AS NUM_POLIZA
,A.NUM_VERSION          AS NUM_VERSION
,CAST(LEAD(NUM_VERSION-1) OVER(PARTITION BY NUM_POLIZA ORDER BY NUM_VERSION) AS SMALLINT) AS NUM_VERSION_NEXT
,A.CVE_PROD_TECNICO     AS CVE_PROD_TECNICO
,A.CVE_PROD_COMERCIAL   AS CVE_PROD_COMERCIAL
,A.CVE_PROD_VENTA       AS CVE_PROD_VENTA
,A.POVASEGP             AS PCT_DESCUENTO_PREVIO                             /*PORCENTAJE DESCUENTO PREVIO                       */
,A.PODEXPSI             AS PCT_DESCUENTO_EXP_SINIESTRAL                     /*DESCUENTO EXP SINIESTRAL                          */
,A.TCVTVACO             AS CVE_VRS_TARIFA_VAL_CONVENIDO                     /*VERSION DE TARIFA VALOR CONVENIDO                 */
,A.TCRAMO               AS CVE_RAMO_AUTOMOVIL                               /*RAMO DE AUTOMOVILES                               */
,A.TCVERFCP             AS CVE_VRS_FACT_CODIGOP                             /*VERSION DE FACTOR DEL CODIGO POSTAL               */
,A.VADESVOL             AS PCT_VALOR_DESCUENTO_VOLUMEN                      /*VALOR DEL DESCUENTO POR VOLUMEN                   */
,A.POFUEPRO             AS PCT_DESCUENTO_FUERZA_PRODUCTORA                  /*DESCUENTO FUERZA PRODUCTORA                       */
,A.TCSEGTO              AS CVE_SEGMENTO_AUTOMOVIL                           /*SEGMENTO AUTOMOVILES                              */
,A.CDTIPINC             AS CVE_INCLUSION                                    /*TIPO DE INCLUSION                                 */
,A.CDFACPER             AS CVE_VRS_FACT_PERSONA                             /*TIPO DE VERSION FACTOR PERSONA                    */
,A.INDNEGLI             AS CVE_NEGOCIO_LICITADO                             /*INDICADOR DE NEGOCIO LICITADO                     */
,A.CDFRACGA             AS CVE_FRACCION_GASTOS                              /*INDICA SI SE FRACCIONAN LOS GASTOS                */
,A.CDDERPOL             AS CVE_VRS_DERECHO_POLIZA                           /*TIPO DE VERSION DE DERECHOS DE POLIZA             */
,A.CDNUMFEC             AS CVE_REGISTRO                                     /*NUMERO DE REGISTRO                                */
,A.INDESCLI             AS CVE_CLIENTE_LEAL                                 /*DESCUENTO CLIENTE LEAL  (DESC CLIENTE INTEGR )    */
,A.CDCONSAD             AS CVE_CONTRATO_SADE_APF                            /*CONTRATO SADE APF                                 */
,A.FECHAEVO             AS FCH_TARIFA_EVOLUCION                             /*FECHA TARIFA EVOLUCION                            */
,A.POMEDCON             AS PTC_DESCUENTO_MEDICO_CONVENIO                    /*DESCUENTO EN MEDICO EN CONVENIO                   */
,A.CDTIPTAR             AS CVE_TARIFA_AUTO                                  /*TIPO DE TARIFA AUTOS                              */
,A.CDTITVAC             AS CVE_TARIFA_VALOR_CONVENIDO                        /*TIPO DE TARIFA VALOR CONVENIDO                    */
,A.CDDEPGUB             AS CVE_DEP_GUBERNAMENTAL                            /*CODIGO DE DEPENDENCIA GUBERNAMENTAL               */
,F.DSLDEPGUB            AS DESC_DEP_GUBERNAMENTAL                           /*DESCRIPCION CODIGO DE DEPENDENCIA GUBERNAMENTAL   */
,A.CDSUBDEG             AS CVE_SUB_DEP_GUBERNAMENTAL                        /*CODIGO SUBDEPENDENCIA GUBERNAMENTAL               */
,G.DSLSUBDEG            AS DESC_SUB_DEP_GUBERNAMENTAL                       /*DESCRIPCION CODIGO SUBDEPENDENCIA GUBERNAMENTAL   */
,A.DSVERTAR             AS DESC_TRANSFORMACION                              /*VERSION DE TRANSFORMACION                         */
,A.TCLNVER              AS CVE_VRS_LINEA_NARANJA                            /*VERSION DE LINEA NARANJA                          */
,A.CDEVOSAD             AS CVE_IDENTIFICADOR_SADE_EVO                       /*CODIGO IDENTIFICADOR SADE EVOLUCION               */
,A.PODESCLI             AS PTC_DESCUENTO_CLIENTE_INT                        /*DESCUENTO CLIENTE INTEGRAL                        */
,A.VADESGIM             AS PTC_DESCUENTO_GIM                                /*VALOR DEL DESCUENTO GIM                           */
,A.TCNUMVER             AS CVE_VRS_TARIFA                                   /*VERSION DE TARIFA                                 */
,A.TCMAPYME             AS CVE_MARCA_PYME                                   /*MACA PYME                                         */
,H.DSCMAPYME            AS DESC_MARCA_PYME                                  /*DESCRIPCION MARCA PYME                            */
,A.CDFACCP              AS CVE_TIPO_VRS_FACT_CODIGOP                        /*TIPO DE VERSION FACTOR CODIGO POSTAL              */
,A.VADESCAR             AS PTC_DESCUENTO_CARTERA                            /*VALOR DEL DESCUENTO POR CARTERA                   */
,A.VAGESCOM             AS PTC_GESTION_COMERCIAL                            /*GESTION COMERCIAL                                 */
,A.TCTIPOES             AS CVE_AGRUPACION_POLIZAS                           /*ESTRUCTURA AGRUPACION DE POLIZAS                  */
,A.CDPROCON             AS CVE_PROD_CONFIGURADOR                            /*CODIGO PRODUCTO DEL CONFIGURADOR                  */
,E.DSLPROCON            AS DESC_PROD_CONFIGURADOR                           /*DESCRIPCION CODIGO PRODUCTO DEL CONFIGURADOR      */
,A.CDPROMAU             AS CVE_CODIGO_PROMOCION                             /*CODIGO DE PROMOCION                               */
,D.DSLPROMAU            AS DESC_CODIGO_PROMOCION                            /*DESCRIPCION CODIGO DE PROMOCION                   */
,A.CDIDCAMP             AS CVE_CAMPANIA_APLICADA                            /*CODIGO DE CAMPANIA APLICADA                     */       
,A.PODESCAM             AS PTC_DESCUENTO_CAMPANIA                           /*PORCENTAJE DE DESCUENTO DE CAMPANIA               */
,A.INSERCON             AS CVE_SERVICION_CONEXOS                            /*INDICADOR DE SERVICIOS CONEXOS                    */
,A.CDAGRNEG             AS CVE_AGRUPACION_NEGOCIO                           /*AGRUPACION DE NEGOCIO                             */
,A.TCFACPER             AS CVE_VRS_FACTOR_PERSONA                           /*VERSION DE FACTOR PERSONA                         */
,A.TCSRAMO              AS CVE_SUBRAMO_AUTOMOVIL                            /*SUBRAMO DE AUTOMOVILES                            */
,B.DSSRAMO              AS DESC_SUBRAMO_AUTOMOVIL                           /*DESCRIPCION SUBRAMO DE AUTOMOVILES                */
,A.CDCANACC             AS CVE_CANAL_ACCESO_EVO                             /*CANAL DE ACCESO EVOLUCION                         */
,A.DSNECOME             AS DESC_NEGOCIO_COMERCIAL                           /*NEGOCIO COMERCIAL                                 */
,A.VAEXCRIE             AS PTC_EXCEPCION_RIESGO                             /*EXCEPCION RIESGO                                  */
,A.CDTIPPLA             AS CVE_TIPO_PLAN                                    /*TIPO DE PLAN                                      */
,A.VADESIGU             AS PTC_DESCUENTO_IGUALACION                         /*VALOR DEL DESCUENTO POR IGUALACION                */
,A.TCVADEPA             AS CVE_DESCUENTO_PAGO_INMEDIATO                     /*DESCUENTO PAGO INMEDIATO                          */
,A.FECHATAR             AS FCH_TRANSFORMACION                               /*FECHA DE TRANSFORMACION                           */
,A.TCRECPPF             AS CVE_VRS_RPF                                      /*VERSION DE RECARGO POR PAGO FRACCIONADO           */
,A.PODESMVE             AS PTC_CLIENTE_LEAL                                 /*DESCUENTO CLIENTE LEAL  (POR DES MAS 1 VEH)       */                   
,A.CDNEGOPE             AS CVE_NEGOCIO_OPERABLE                             /*CODIGO DEL NEGAOCIO OPERABLE                      */
,'S/I' /*C.DSNEGOPE*/   AS DESC_NEGOCIO_OPERABLE                            /*Queda pendiente por parte de Anaximandro          */
,A.INEDAMCO             AS CVE_CONDUCTOR_JOVEN_DECLARADO                    /*INDICADOR CONDUCTOR JOVEN DECLARADO               */
,A.CDGPO2DW             AS CVE_GRUPO2_DWH                                   /*GRUPO 2 DATAWAREHOUSE                             */
,A.INSCORIN             as ban_scorin
,A.IDMD5                AS IDMD5
,A.TSULTMOD             AS TSULTMOD
,A.SISTORIG             AS SISTORIG
,A.FECHAAUD             AS FECHAAUD
FROM BDDLALM.AUT_ELEMENTO_POLIZA A
 LEFT JOIN (SELECT TRIM(CDELEMEN) AS TCSRAMO, TRIM(DSELEMEN) AS DSSRAMO FROM BDDLCRU.KTCTGET WHERE UPPER(TRIM(CDTABLA)) = 'KTPT2QG' AND TRIM(CDIDIOMA) ='ES' ) B
 ON TRIM(A.TCSRAMO) = TRIM(B.TCSRAMO)
 --  LEFT JOIN (SELECT DISTINCT TRIM(ID_NEGOCIO_OPERABLE) AS CDNEGOPE, TRIM(NEGOCIO_OPERABLE) AS DSNEGOPE FROM BDDLDES.SBI_CDN_NEGOCIO_OPERABLE ) C   /* Pendiente de Revisar */
--    ON TRIM(A.CDNEGOPE) = TRIM(C.CDNEGOPE)
 LEFT JOIN (SELECT TRIM(CDELEMEN) AS CDPROMAU,SUBSTR(DSELEMEN,1,20) AS DSCPROMAU,SUBSTR(DSELEMEN,21,150) AS DSLPROMAU FROM BDDLCRU.KTCTGET WHERE UPPER(TRIM(CDTABLA)) = 'KTPT04S' ) D 
 ON TRIM(A.CDPROMAU) = TRIM(D.CDPROMAU)
 LEFT JOIN (SELECT TRIM(CDELEMEN) AS CDPROCON,SUBSTR(DSELEMEN,1,20) AS DSCPROCON,SUBSTR(DSELEMEN,21,150) AS DSLPROCON FROM BDDLCRU.KTCTGET WHERE UPPER(TRIM(CDTABLA)) = 'KTPT04S' ) E  
 ON TRIM(A.CDPROCON) = TRIM(E.CDPROCON)
 LEFT JOIN (SELECT TRIM(CDELEMEN) AS CDDEPGUB,SUBSTR(DSELEMEN,1,20) AS DSCDEPGUB,SUBSTR(DSELEMEN,21,150) AS DSLDEPGUB FROM BDDLCRU.KTCTGET WHERE UPPER(TRIM(CDTABLA)) = 'KTPT04S' ) F
 ON TRIM(A.CDDEPGUB) = TRIM(F.CDDEPGUB)
 LEFT JOIN (SELECT TRIM(CDELEMEN) AS CDSUBDEG,SUBSTR(DSELEMEN,1,20) AS DSCSUBDEG,SUBSTR(DSELEMEN,21,150) AS DSLSUBDEG FROM BDDLCRU.KTCTGET WHERE UPPER(TRIM(CDTABLA)) = 'KTPT04S' ) G
 ON TRIM(A.CDSUBDEG) = TRIM(G.CDSUBDEG)
 LEFT JOIN (SELECT TRIM(CDELEMEN) AS TCMAPYME,SUBSTR(DSELEMEN,1,20) AS DSCMAPYME,SUBSTR(DSELEMEN,21,150) AS DSLMAPYME FROM BDDLCRU.KTCTGET WHERE UPPER(TRIM(CDTABLA)) = 'KTPT04S' ) H
 ON TRIM(A.TCMAPYME) = TRIM(H.TCMAPYME);

------------------------------------------------------------------------------------------
--#### PASO 2
--###CREA POLIZARIO_AUT_POLIZA (sabana con todos los valores incluyendo nullos)
--TAKE 5 MIN
--#se genero un script para generar esta tabla
------------------------------------------------------------------------------------------


--CREA TABLA FISICA CON TODAS LAS VERSIONES

DROP TABLE IF EXISTS BDDLALM.AUT_ELEMENTO_POLIZA_TP;

CREATE TABLE BDDLALM.AUT_ELEMENTO_POLIZA_TP STORED AS PARQUET
AS 
SELECT POL.NUM_POLIZA_POLIZARIO NUM_POLIZA, POL.NUM_VERSION_POLIZARIO NUM_VERSION, COM.CVE_PROD_TECNICO, COM.CVE_PROD_COMERCIAL, COM.CVE_PROD_VENTA
, COM.PCT_DESCUENTO_PREVIO, COM.PCT_DESCUENTO_EXP_SINIESTRAL, COM.CVE_VRS_TARIFA_VAL_CONVENIDO, COM.CVE_RAMO_AUTOMOVIL, COM.CVE_VRS_FACT_CODIGOP
, COM.PCT_VALOR_DESCUENTO_VOLUMEN, COM.PCT_DESCUENTO_FUERZA_PRODUCTORA, COM.CVE_SEGMENTO_AUTOMOVIL, COM.CVE_INCLUSION, COM.CVE_VRS_FACT_PERSONA
, COM.CVE_NEGOCIO_LICITADO, COM.CVE_FRACCION_GASTOS, COM.CVE_VRS_DERECHO_POLIZA, COM.CVE_REGISTRO, COM.CVE_CLIENTE_LEAL, COM.CVE_CONTRATO_SADE_APF
, COM.FCH_TARIFA_EVOLUCION, COM.PTC_DESCUENTO_MEDICO_CONVENIO, COM.CVE_TARIFA_AUTO, COM.CVE_TARIFA_VALOR_CONVENIDO, COM.CVE_DEP_GUBERNAMENTAL, COM.DESC_DEP_GUBERNAMENTAL
, COM.CVE_SUB_DEP_GUBERNAMENTAL, COM.DESC_SUB_DEP_GUBERNAMENTAL, COM.DESC_TRANSFORMACION, COM.CVE_VRS_LINEA_NARANJA, COM.CVE_IDENTIFICADOR_SADE_EVO, COM.PTC_DESCUENTO_CLIENTE_INT
, COM.PTC_DESCUENTO_GIM, COM.CVE_VRS_TARIFA, COM.CVE_MARCA_PYME, COM.DESC_MARCA_PYME, COM.CVE_TIPO_VRS_FACT_CODIGOP, COM.PTC_DESCUENTO_CARTERA, COM.PTC_GESTION_COMERCIAL
, COM.CVE_AGRUPACION_POLIZAS, COM.CVE_PROD_CONFIGURADOR, COM.DESC_PROD_CONFIGURADOR, COM.CVE_CODIGO_PROMOCION, COM.DESC_CODIGO_PROMOCION, COM.CVE_CAMPANIA_APLICADA
, COM.PTC_DESCUENTO_CAMPANIA, COM.CVE_SERVICION_CONEXOS, COM.CVE_AGRUPACION_NEGOCIO
, COM.CVE_VRS_FACTOR_PERSONA, COM.CVE_SUBRAMO_AUTOMOVIL, COM.DESC_SUBRAMO_AUTOMOVIL, COM.CVE_CANAL_ACCESO_EVO, COM.DESC_NEGOCIO_COMERCIAL
, COM.PTC_EXCEPCION_RIESGO, COM.CVE_TIPO_PLAN, COM.PTC_DESCUENTO_IGUALACION
, COM.CVE_DESCUENTO_PAGO_INMEDIATO, COM.FCH_TRANSFORMACION, COM.CVE_VRS_RPF, COM.PTC_CLIENTE_LEAL, COM.CVE_NEGOCIO_OPERABLE, COM.DESC_NEGOCIO_OPERABLE
, COM.CVE_CONDUCTOR_JOVEN_DECLARADO, COM.CVE_GRUPO2_DWH,COM.BAN_SCORIN,COM.IDMD5
, COM.TSULTMOD, COM.SISTORIG, COM.FECHAAUD 
FROM bddltrn.aut_polizario pol
INNER JOIN bddlalm.aut_elemento_poliza_tmp com 
ON POL.NUM_POLIZA_POLIZARIO = COM.NUM_POLIZA 
AND POL.NUM_VERSION_POLIZARIO BETWEEN COM.NUM_VERSION  AND coalesce(COM.NUM_VERSION_NEXT, 1000000)
;

COMPUTE STATS BDDLALM.AUT_ELEMENTO_POLIZA_TP;
