--___________________________________________________________________________________________________________________________________________________________ 
--/                                                 #####    PROYECTO GMM - PADECIMIENTO DECLARADO   ##### 
--| @FECHA DE CREACION:  # 28 de Noviembre del 2019
--| @DOMINIOS:           # INFO
--| @ARCHIVO:            # RFC004913_cnm_padecimiento_declarado-Install.hql
--| @AUTOR:              # creherna
--| @DESCRIPCION:        # Se crea script de pre-instalacion, realiza backup y despues elimina tablas. 
--| @PARAMETROS:         # N/A.
--| @CONSIDERACIONES: 
--|     # Genera tablas de respaldo con el sufijo del rfc.
--\_________________________________________________________________________________________________________________________________________________________/ 
CREATE TABLE IF NOT EXISTS bddltrn.ALM_PADECIMIENTO_DECLARADO_RFC0049313_bkp LIKE bddltrn.ALM_PADECIMIENTO_DECLARADO;
INSERT OVERWRITE TABLE bddltrn.ALM_PADECIMIENTO_DECLARADO_RFC0049313_bkp SELECT * FROM bddlalm.ALM_PADECIMIENTO_DECLARADO;

CREATE TABLE IF NOT EXISTS bddltrn.ALM_PADECIMIENTO_DECLARADOHIS_RFC0049313_bkp LIKE bddlalm.ALM_PADECIMIENTO_DECLARADOHIS;
INSERT OVERWRITE TABLE bddltrn.ALM_PADECIMIENTO_DECLARADOHIS_RFC0049313_bkp SELECT * FROM bddlalm.ALM_PADECIMIENTO_DECLARADOHIS;

CREATE TABLE IF NOT EXISTS bddltrn.STG_GMM_CON_PADECIMIENTO_DECLARADO_DELTA_EXTRACCION_RFC0049313_bkp LIKE bddltrn.STG_GMM_CON_PADECIMIENTO_DECLARADO_DELTA_EXTRACCION;

CREATE TABLE IF NOT EXISTS bddltrn.STG_GMM_CON_PADECIMIENTO_DECLARADO_DELTA_RFC0049313_bkp LIKE bddltrn.STG_GMM_CON_PADECIMIENTO_DECLARADO_DELTA;

CREATE TABLE IF NOT EXISTS bddltrn.STG_GMM_CON_PADECIMIENTO_DECLARADO_DELTA_REGLAS_DUPLICIDAD_RFC0049313_bkp LIKE bddltrn.STG_GMM_CON_PADECIMIENTO_DECLARADO_DELTA_REGLAS_DUPLICIDAD;

--Borra tablas Actuales
DROP TABLE IF EXISTS bddlalm.ALM_PADECIMIENTO_DECLARADO;
DROP TABLE IF EXISTS bddlalm.ALM_PADECIMIENTO_DECLARADOHIS;
DROP TABLE IF EXISTS bddltrn.STG_GMM_CON_PADECIMIENTO_DECLARADO_DELTA_EXTRACCION;
DROP TABLE IF EXISTS bddltrn.STG_GMM_CON_PADECIMIENTO_DECLARADO_DELTA;
DROP TABLE IF EXISTS bddltrn.STG_GMM_CON_PADECIMIENTO_DECLARADO_DELTA_REGLAS_DUPLICIDAD;

--Borra tablas de desarrollo
DROP TABLE IF EXISTS bddlalm.ALM_PADECIMIENTO_DECLARADO_RFC0049313;
DROP TABLE IF EXISTS bddlalm.ALM_PADECIMIENTO_DECLARADO_RFC0049313HIS;
DROP TABLE IF EXISTS bddltrn.STG_GMM_CON_PADECIMIENTO_DECLARADO_DELTA_EXTRACCION_RFC0049313;
DROP TABLE IF EXISTS bddltrn.STG_GMM_CON_PADECIMIENTO_DECLARADO_DELTA_RFC0049313;
DROP TABLE IF EXISTS bddltrn.STG_GMM_CON_PADECIMIENTO_DECLARADO_DELTA_REGLAS_DUPLICIDAD_RFC0049313;