----Paso 0: RESPALDAR TABLA -----

CREATE TABLE BDDLTRN.STG_GMM_CON_ALM_SOLICITUD_DELTA_DUPLICADOS_28_11_19 AS
SELECT * FROM BDDLTRN.STG_GMM_CON_ALM_SOLICITUD_DELTA_FINAL

----Paso 1: VALIDAR QUE SE HAYA LLENADO LA TABLA------

select * from BDDLTRN.STG_GMM_CON_ALM_SOLICITUD_DELTA_DUPLICADOS_28_11_19;

---------paso 2: SACAR EL IMD5 (guardar la salida)-----------
SELECT IDMD5, COUNT(*) AS CNT
FROM BDDLTRN.STG_GMM_CON_ALM_SOLICITUD_DELTA_FINAL
GROUP BY IDMD5
HAVING CNT > 1
LIMIT 300;

------------paso 3: TRUNCAR LA TABLA-------------

TRUNCATE TABLE BDDLTRN.STG_GMM_CON_ALM_SOLICITUD_DELTA_FINAL

-----Paso 4: INSERTAR REGISTROS SIN EL DUPLICADO------------

INSERT INTO TABLE BDDLTRN.STG_GMM_CON_ALM_SOLICITUD_DELTA_FINAL
SELECT * FROM BDDLTRN.STG_GMM_CON_ALM_SOLICITUD_DELTA_DUPLICADOS_28_11_19
WHERE IDMD5 NOT IN ('bd77b98afa0493e1ff97c65eeb08f99e');

--------Paso 5: INSERTAR CON EL NUMERO SOLICITUD TRAMITE---------
INSERT INTO TABLE BDDLTRN.STG_GMM_CON_ALM_SOLICITUD_DELTA_FINAL
SELECT * FROM BDDLTRN.STG_GMM_CON_ALM_SOLICITUD_DELTA_DUPLICADOS_28_11_19
WHERE IDMD5 IN ('bd77b98afa0493e1ff97c65eeb08f99e') AND NUM_SOLICITUD_TRAMITE = 17


---------paso 6: VALIDAR, DEBE TRAER REGISTROS 0-----------
SELECT IDMD5, COUNT(*) AS CNT
FROM BDDLTRN.STG_GMM_CON_ALM_SOLICITUD_DELTA_FINAL
GROUP BY IDMD5
HAVING CNT > 1
LIMIT 300;

-----Paso 7: EJECUTAR DESDE CERO EL CDC CON GMMCONTRA-----------
-----Paso 8: UNA VEZ TERMINADO EL CDC, SE DEBE IR POR EL LADO OTRO LADO (SIN DUPLICADOS)--------
-----Paso 9: ENTRAR A LA CUENTA DE USRSUP; WORKFLOWS -> EDITOR; BUSCAR y ENTRAR EN EL WORKFLOW WKF_GMM_SOLICITUD---------
-----Paso 10: LANZAR LOS ULTIMOS 3 (DESPUES DEL CDC, se anexa imagen, figura 1); DE UNO EN UNO, SE LANZA UNO, MARCA VERDE Y REGRESAR A LA PAGINA PARA LANZAR EL OTRO (figura 1.1,1.2,1.3)
-----Paso 11: PEDIR FORCE OK