ALTER TABLE bddldes.aut_siniestro_cob_afecta_insumo_comp RENAME TO bddldes.aut_siniestro_cob_afecta_insumo_comp_REQ0143537;
ALTER TABLE bddldes.aut_siniestro_cob_afecta_insumo_nvos_parquet RENAME TO bddldes.aut_siniestro_cob_afecta_insumo_nvos_parquet_REQ0143537;
ALTER TABLE bddlalm.aut_reserva_salvamentos RENAME TO bddlalm.aut_reserva_salvamentos_REQ0143537;
ALTER TABLE bddlalm.aut_siniestro_afectado RENAME TO bddlalm.aut_siniestro_afectado_REQ0143537;
ALTER TABLE bddlalm.aut_siniestro RENAME TO bddlalm.aut_siniestro_REQ0143537;
ALTER TABLE bddldes.aut_mec_reserva_siniestro_parquet RENAME TO bddldes.aut_mec_reserva_siniestro_parquet_REQ0143537;

ALTER TABLE bddldes.aut_siniestro_cob_afecta_insumo_comp RENAME TO bddldes.aut_siniestro_cob_afecta_insumo_comp_mvm_f1;
ALTER TABLE bddldes.aut_siniestro_cob_afecta_insumo_nvos_parquet RENAME TO bddldes.aut_siniestro_cob_afecta_insumo_nvos_parquet_mvm_f1;
ALTER TABLE bddlalm.aut_reserva_salvamentos RENAME TO bddlalm.aut_reserva_salvamentos_mvm_f1;
ALTER TABLE bddlalm.aut_siniestro_afectado RENAME TO bddlalm.aut_siniestro_afectado_mvm_f1;
ALTER TABLE bddlalm.aut_siniestro RENAME TO bddlalm.aut_siniestro_mvm_f1;
ALTER TABLE bddldes.aut_mec_reserva_siniestro_parquet RENAME TO bddldes.aut_mec_reserva_siniestro_parquet_mvm_f1;

ALTER TABLE bddldes.aut_siniestro_cob_afecta_insumo_comp_REQ0143537 RENAME TO bddldes.aut_siniestro_cob_afecta_insumo_comp;
ALTER TABLE bddldes.aut_siniestro_cob_afecta_insumo_nvos_parquet_REQ0143537 RENAME TO bddldes.aut_siniestro_cob_afecta_insumo_nvos_parquet;
ALTER TABLE bddlalm.aut_reserva_salvamentos_REQ0143537 RENAME TO bddlalm.aut_reserva_salvamentos;
ALTER TABLE bddlalm.aut_siniestro_afectado_REQ0143537 RENAME TO bddlalm.aut_siniestro_afectado;
ALTER TABLE bddlalm.aut_siniestro_REQ0143537 RENAME TO bddlalm.aut_siniestro;
ALTER TABLE bddldes.aut_mec_reserva_siniestro_parquet_REQ0143537 RENAME TO bddldes.aut_mec_reserva_siniestro_parquet;

