select
	upper(OPERATION_TEXT)
from
	nav.HIVE_AUDIT_EVENTS_2020_01_10
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.HIVE_AUDIT_EVENTS_2020_01_11
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.HIVE_AUDIT_EVENTS_2020_01_12
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.HIVE_AUDIT_EVENTS_2020_01_13
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.HIVE_AUDIT_EVENTS_2020_01_14
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.HIVE_AUDIT_EVENTS_2020_01_15
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.HIVE_AUDIT_EVENTS_2020_01_16
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.HIVE_AUDIT_EVENTS_2020_01_17
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.HIVE_AUDIT_EVENTS_2020_01_18
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.HIVE_AUDIT_EVENTS_2020_01_19
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.HIVE_AUDIT_EVENTS_2020_01_20
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.IMPALA_AUDIT_EVENTS_2020_01_10
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.IMPALA_AUDIT_EVENTS_2020_01_11
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.IMPALA_AUDIT_EVENTS_2020_01_12
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.IMPALA_AUDIT_EVENTS_2020_01_13
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.IMPALA_AUDIT_EVENTS_2020_01_14
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.IMPALA_AUDIT_EVENTS_2020_01_15
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.IMPALA_AUDIT_EVENTS_2020_01_16
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.IMPALA_AUDIT_EVENTS_2020_01_17
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.IMPALA_AUDIT_EVENTS_2020_01_18
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.IMPALA_AUDIT_EVENTS_2020_01_19
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%'
UNION
select
	upper(OPERATION_TEXT)
from
	nav.IMPALA_AUDIT_EVENTS_2020_01_20
where
	OPERATION = 'QUERY'
	and UPPER(OPERATION_TEXT) like '%INSERT%BDDLCRU.KTOM41H%';