select
	db.NAME AS ESQUEMA,
	t.TBL_NAME AS TABLA,
	t.TBL_TYPE AS TIPO_TABLA,
	CASE WHEN CAST(d.PARAM_VALUE AS UNSIGNED) <= 1000000000 THEN CONCAT(CAST(CAST(d.PARAM_VALUE AS UNSIGNED)/ 1048576 as CHAR(50)), ' MB')
	WHEN CAST(d.PARAM_VALUE AS UNSIGNED) > 1000000000
	and CAST(d.PARAM_VALUE AS UNSIGNED) < 1000000000000 THEN CONCAT(CAST(CAST(d.PARAM_VALUE AS UNSIGNED)/ 1073741824 as CHAR(50)), ' GB')
	WHEN CAST(d.PARAM_VALUE AS UNSIGNED) >= 1000000000000 THEN CONCAT(CAST(CAST(d.PARAM_VALUE AS UNSIGNED)/ 1099511627776 as CHAR(50)), ' TB') END as SIZEREPLICAX1,
	CASE WHEN CAST(d.PARAM_VALUE AS UNSIGNED)* 3 <= 1000000000 THEN CONCAT(CAST(CAST(d.PARAM_VALUE AS UNSIGNED)* 3 / 1048576 as CHAR(50)), ' MB')
	WHEN (CAST(d.PARAM_VALUE AS UNSIGNED)* 3) > 1000000000
	and CAST(d.PARAM_VALUE AS UNSIGNED)* 3 < 1000000000000 THEN CONCAT(CAST(CAST(d.PARAM_VALUE AS UNSIGNED)* 3 / 1073741824 as CHAR(50)), ' GB')
	WHEN CAST(d.PARAM_VALUE AS UNSIGNED)* 3 >= 1000000000000 THEN CONCAT(CAST(CAST(d.PARAM_VALUE AS UNSIGNED)* 3 / 1099511627776 as CHAR(50)), ' TB') END as SIZEREPLICAX3,
	CAST(dd.PARAM_VALUE AS UNSIGNED) as numRows,
	CONCAT('Compute Stats ', db.NAME, '.', t.TBL_NAME, ';') as ESTADISTICAS_IMPALA,
	CASE WHEN t.TBL_TYPE = 'EXTERNAL_TABLE' THEN CONCAT("ALTER TABLE ", db.NAME, ".", t.TBL_NAME, " SET TBLPROPERTIES(' EXTERNAL '=' FALSE ');") END as TO_INTERNAL_HIVE,
	CONCAT('DROP TABLE ', db.NAME, '.', t.TBL_NAME, ';') AS DROP_HIVE
from
	metastore.TBLS t
left join metastore.TABLE_PARAMS d on
	t.TBL_ID = d.TBL_ID
	and d.PARAM_KEY = 'totalSize'
left join metastore.TABLE_PARAMS dd on
	t.TBL_ID = dd.TBL_ID
	and dd.PARAM_KEY = 'numRows'
left join metastore.DBS db on
	t.DB_ID = db.DB_ID
where
	CAST(d.PARAM_VALUE AS UNSIGNED) = 0
	and CAST(dd.PARAM_VALUE AS UNSIGNED) = 0
order by
	2;