select
	db.NAME AS ESQUEMA,
	t.TBL_NAME AS TABLA,
	t.TBL_TYPE AS TIPO_TABLA,
	str_to_date(from_unixtime(t.CREATE_TIME),
	'%Y-%m-%d') as CREATE_TIME, 
	str_to_date(from_unixtime(dd.PARAM_VALUE),
	'%Y-%m-%d %h:%i:%s') as LAST_DDL_TIME,
	CASE WHEN CAST(d.PARAM_VALUE AS UNSIGNED) <= 1000000000 THEN CONCAT(CAST(CAST(d.PARAM_VALUE AS UNSIGNED)/ 1048576 as CHAR(50)), ' MB')
	WHEN CAST(d.PARAM_VALUE AS UNSIGNED) > 1000000000
	and CAST(d.PARAM_VALUE AS UNSIGNED) < 1000000000000 THEN CONCAT(CAST(CAST(d.PARAM_VALUE AS UNSIGNED)/ 1073741824 as CHAR(50)), ' GB')
	WHEN CAST(d.PARAM_VALUE AS UNSIGNED) >= 1000000000000 THEN CONCAT(CAST(CAST(d.PARAM_VALUE AS UNSIGNED)/ 1099511627776 as CHAR(50)), ' TB') END as SIZEREPLICAX1,
	CASE WHEN CAST(d.PARAM_VALUE AS UNSIGNED)* 3 <= 1000000000 THEN CONCAT(CAST(CAST(d.PARAM_VALUE AS UNSIGNED)* 3 / 1048576 as CHAR(50)), ' MB')
	WHEN (CAST(d.PARAM_VALUE AS UNSIGNED)* 3) > 1000000000
	and CAST(d.PARAM_VALUE AS UNSIGNED)* 3 < 1000000000000 THEN CONCAT(CAST(CAST(d.PARAM_VALUE AS UNSIGNED)* 3 / 1073741824 as CHAR(50)), ' GB')
	WHEN CAST(d.PARAM_VALUE AS UNSIGNED)* 3 >= 1000000000000 THEN CONCAT(CAST(CAST(d.PARAM_VALUE AS UNSIGNED)* 3 / 1099511627776 as CHAR(50)), ' TB') END as SIZEREPLICAX3
from
	metastore.TBLS t
left join metastore.TABLE_PARAMS d on
	t.TBL_ID = d.TBL_ID
	and d.PARAM_KEY = 'totalSize'
left join metastore.TABLE_PARAMS dd on
	t.TBL_ID = dd.TBL_ID
	and dd.PARAM_KEY = 'transient_lastDdlTime'
left join metastore.DBS db on
	t.DB_ID = db.DB_ID
where
	t.TBL_NAME like '%cnm%'
	and db.NAME = 'bddlapr'
	and t.TBL_TYPE <> 'VIRTUAL_VIEW'
UNION
SELECT
	'',
	'',
	'',
	'',
	'TOTAL SIZE',
	CONCAT(CAST(SUM(CAST(d.PARAM_VALUE AS UNSIGNED)) / 1099511627776 as CHAR(50)), ' TB') as SIZEREPLICAX1,
	CONCAT(CAST(SUM(CAST(d.PARAM_VALUE AS UNSIGNED))* 3 / 1099511627776 as CHAR(50)), ' TB') as SIZEREPLICAX3
from
	metastore.TBLS t
left join metastore.TABLE_PARAMS d on
	t.TBL_ID = d.TBL_ID
	and d.PARAM_KEY = 'totalSize'
left join metastore.DBS db on
	t.DB_ID = db.DB_ID
where
	t.TBL_NAME like '%cnm%'
	and db.NAME = 'bddlapr'
	and t.TBL_TYPE <> 'VIRTUAL_VIEW'
